name: Build Proxmox template

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

permissions:
  contents: write

jobs:
  packer-build:
    name: Packer build
    runs-on: self-hosted
    outputs:
      manifest: ${{ steps.get-manifest.outputs.manifest }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Packer
        uses: hashicorp/setup-packer@v3
        with:
          version: latest

      - name: Initialize Packer
        run: packer init -force -upgrade .

      - name: Build Proxmox template
        env:
          PKR_VAR_proxmox_api_url: ${{ vars.PROXMOX_API_URL }}
          PKR_VAR_proxmox_api_token_id: ${{ secrets.PROXMOX_API_TOKEN_ID }}
          PKR_VAR_proxmox_api_token_secret: ${{ secrets.PROXMOX_API_TOKEN_SECRET }}
          PKR_VAR_timezone: ${{ vars.TIMEZONE }}
          PKR_VAR_apt_mirror: |
            {
              "protocol": "${{ vars.APT_MIRROR_PROTOCOL }}",
              "country": "${{ vars.APT_MIRROR_COUNTRY }}",
              "hostname": "${{ vars.APT_MIRROR_HOSTNAME }}",
              "directory": "${{ vars.APT_MIRROR_DIRECTORY }}"
            }
        run: packer build -force .

      - name: Get Packer build manifest
        id: get-manifest
        run: |
          echo 'manifest<<EOF' >> $GITHUB_OUTPUT
          cat packer-manifest.json >> $GITHUB_OUTPUT
          echo -e '\nEOF' >> $GITHUB_OUTPUT

  create-release:
    name: Create release
    runs-on: ubuntu-latest
    needs: packer-build
    steps:
      - run: echo -e ${{ toJSON(needs.packer-build.outputs.manifest) }} > packer-manifest.json

      - uses: softprops/action-gh-release@v2
        with:
          tag_name: '${{ fromJSON(needs.packer-build.outputs.manifest).builds[0].custom_data.vm_name }}'
          name: Packer Build ${{ github.run_number }}
          files: packer-manifest.json
          make_latest: true

  trigger-terraform:
    name: Trigger Terraform plan
    runs-on: ubuntu-latest
    needs: packer-build
    steps:
      - run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.TERRAFORM_DISPATCH_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -d '{"event_type":"packer-build-success","client_payload":${{ needs.packer-build.outputs.manifest }}}' \
            https://api.github.com/repos/MrStarktastic/homelab-terraform/dispatches
