name: Build Proxmox template

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

permissions:
  contents: write

jobs:
  packer-build:
    name: Packer build
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Packer
        uses: hashicorp/setup-packer@v3
        with:
          version: latest

      - name: Initialize Packer
        run: packer init -force -upgrade .

      - name: Build Proxmox template
        env:
          PKR_VAR_proxmox_api_url: ${{ vars.PROXMOX_API_URL }}
          PKR_VAR_proxmox_api_token_id: ${{ secrets.PROXMOX_API_TOKEN_ID }}
          PKR_VAR_proxmox_api_token_secret: ${{ secrets.PROXMOX_API_TOKEN_SECRET }}
          PKR_VAR_timezone: ${{ vars.TIMEZONE }}
          PKR_VAR_apt_mirror: |
            {
              "protocol": "${{ vars.APT_MIRROR_PROTOCOL }}",
              "country": "${{ vars.APT_MIRROR_COUNTRY }}",
              "hostname": "${{ vars.APT_MIRROR_HOSTNAME }}",
              "directory": "${{ vars.APT_MIRROR_DIRECTORY }}"
            }
        run: packer build -force .

      - run: |
          echo 'MANIFEST<<EOF' >> $GITHUB_ENV
          cat packer-manifest.json >> $GITHUB_ENV
          echo -e '\nEOF' >> $GITHUB_ENV

      - name: Create release
        id: release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: '${{ fromJson(env.MANIFEST).builds[0].custom_data.vm_name }}'
          name: Packer Build ${{ github.run_number }}
          files: packer-manifest.json
          make_latest: true
