name: Build Proxmox template

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

permissions:
  contents: write

jobs:
  packer-build:
    name: Packer build
    runs-on: self-hosted
    outputs:
      manifest: ${{ steps.get-manifest.outputs.manifest }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Packer
        uses: hashicorp/setup-packer@v3
        with:
          version: latest

      - name: Initialize Packer
        run: packer init -force -upgrade .

      - name: Build Proxmox template
        env:
          PKR_VAR_proxmox_api_url: ${{ vars.PROXMOX_API_URL }}
          PKR_VAR_proxmox_api_token_id: ${{ secrets.PROXMOX_API_TOKEN_ID }}
          PKR_VAR_proxmox_api_token_secret: ${{ secrets.PROXMOX_API_TOKEN_SECRET }}
          PKR_VAR_timezone: ${{ vars.TIMEZONE }}
          PKR_VAR_apt_mirror: |
            {
              "protocol": "${{ vars.APT_MIRROR_PROTOCOL }}",
              "country": "${{ vars.APT_MIRROR_COUNTRY }}",
              "hostname": "${{ vars.APT_MIRROR_HOSTNAME }}",
              "directory": "${{ vars.APT_MIRROR_DIRECTORY }}"
            }
        run: packer build -force .

      - name: Get Packer build manifest
        id: get-manifest
        run: |
          echo 'manifest<<EOF' >> $GITHUB_OUTPUT
          cat packer-manifest.json >> $GITHUB_OUTPUT
          echo -e '\nEOF' >> $GITHUB_OUTPUT

  create-release:
    name: Create release
    runs-on: ubuntu-latest
    needs: packer-build
    steps:
      - run: echo -e ${{ toJSON(needs.packer-build.outputs.manifest) }} > manifest.json

      - uses: softprops/action-gh-release@v2
        with:
          tag_name: '${{ fromJSON(needs.packer-build.outputs.manifest).builds[0].custom_data.vm_name }}'
          name: Packer Build ${{ github.run_number }}
          files: manifest.json
          make_latest: true

  push-manifest:
    name: Push to homelab-terraform repo
    runs-on: ubuntu-latest
    needs: packer-build
    steps:
      - name: Checkout Terraform repository
        uses: actions/checkout@v3
        with:
          repository: MrStarktastic/homelab-terraform
          token: ${{ secrets.TERRAFORM_DISPATCH_TOKEN }}
      
      - name: Create branch and PR for manifest file
        env:
          GITHUB_TOKEN: ${{ secrets.TERRAFORM_DISPATCH_TOKEN }}
        run: |
          git config user.name "GitHub Actions (Packer)"
          git config user.email "actions.packer@github.com"

          BRANCH_NAME=packer-build-${{ github.run_number }}
          git checkout -b $BRANCH_NAME || git checkout origin/$BRANCH_NAME
          echo -e ${{ toJSON(needs.packer-build.outputs.manifest) }} > packer-manifest.json
          git add packer-manifest.json
          git commit -m "Update Packer manifest file - ${{ github.run_number }}" || echo 'No changes to commit'
          git push -u origin $BRANCH_NAME

          if [ -z $(gh pr list --head $BRANCH_NAME --json number --jq '.[0].number') ]; then
            gh pr create \
              --base main \
              --head $BRANCH_NAME \
              --title "Update Packer manifest file" \
              --body "This PR updates the Packer manifest file with the latest build information."
          else
            echo "PR already exists. Skipping creation."
          fi
