name: Validate Packer template

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'renovate.json'

permissions:
  contents: write

jobs:
  validate:
    name: Validate Packer template
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Packer
        uses: hashicorp/setup-packer@v3
        with:
          version: latest

      - name: Validate
        env:
          PACKER_GITHUB_API_TOKEN: ${{ secrets.PACKER_GITHUB_API_TOKEN }}
          # Make sure that validate does not fail due to unset variables
          PKR_VAR_proxmox_api_url: 'https://proxmox.example.com:8006/api2/json'
          PKR_VAR_proxmox_api_token_id: 'id'
          PKR_VAR_proxmox_api_token_secret: 'secret'
        run: |
          packer init -force -upgrade .
          packer validate .
