name: Validate and format Packer template

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'renovate.json'

permissions:
  contents: write

jobs:
  validate:
    name: Validate Packer template
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Packer
        uses: hashicorp/setup-packer@v3
        with:
          version: latest

      - name: Validate
        env:
          # Make sure that validate does not fail due to unset variables
          PKR_VAR_proxmox_api_url: 'https://proxmox.example.com:8006/api2/json'
          PKR_VAR_proxmox_api_token_id: 'id'
          PKR_VAR_proxmox_api_token_secret: 'secret'
        run: |
          packer init -force -upgrade .
          packer validate .
  
  format:
    name: Format Packer files
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Packer
        uses: hashicorp/setup-packer@v3
        with:
          version: latest

      - name: Format
        id: fmt
        run: |
          CHANGED_FILES=$(packer fmt -recursive .)
          echo "changed_files<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGED_FILES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Commit & push formatting changes
        if: steps.fmt.outputs.changed_files != ''
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          git add .
          git commit -m "style: packer fmt"
          git push -f origin HEAD:"${{ github.head_ref || github.ref_name }}"
